### PR TITLE
Just wanted to do some code style stuff... ended up in refactoring

### PR DESCRIPTION
**Pull request by MrKrautee**
Just wanted to do some code style stuff ... ended up in refactoring the whole sdk...
Sorry for those big changes at once, but in my opinion its really really necessary to bring the development of this api further. 

Most stuff was simplifying relations and take care of the imports which were misused in some cases and for sure to use python in the python way.
Now we have clear relations and a clean _pythonic_ code. The usage of the api didn't change at all BUT now you have to do the imports right. See `tests/` or `how-tos/`. Also look at `README.md`

Since I finished it just now(_its perfectly working, though_), this should be only a preview. Just to let you know there is something going on and **to get feedback from you**.

Even those changes are massiv (but very healthy and important in my opinion), i ask you to consider it and give it a try.

### CODE REVIEW

**Comment by Pfed-prog** [comment]
Tbh, your implementation is much better

**Comment by MrKrautee** [comment]
I will merge all changes in my branch, if someone has trouble merging it ...
Its really worth it.

**Comment by Pfed-prog** [comment]
Just to save you some further trouble, the dev team on this repo is a bit weird. They responded to my pr as "Several changes have been made which makes this PR obsolete". After some back and forth on Discord got this:
Hey, I just talked with python developer and here is the response:
"I don't use Discord ... he can contact me via GitHub (momipsl) or email (mark@casperlabs.io).
FYI I will be pretty strict with PR merging.  I will review each one and unless they add real value they will be rejected.
[11:22 AM]
Try contacting him directly.  His name is Mark Greenslade"

**Comment by MrKrautee** [comment]
Ah oK. We will see. I think no one can doubt that this PR brings real (important) value to this projects.

**Comment by Pfed-prog** [comment]
Here is also useful resource for launching local network for testing https://docs.casperlabs.io/en/latest/dapp-dev-guide/setup-nctl.html

**Comment by MrKrautee** [comment]
Thxs a lot but already there, in [README.md](https://github.com/MrKrautee/casper-python-sdk#installing-a-local-test-nctl-network)

**Comment by Pfed-prog** [comment]
Since we are working on this repo, could you tell me whether you got all tests successful. I got error in queries2 and serialisation3.

**Comment by MrKrautee** [comment]
all tests should run except that one in serialisation3, there is some kind of bug. But better make a issue for those kind of questions. this is not the topic here ;)

**Comment by momipsl** [comment]
1.  v0.9.1 has just been released that supersedes a lot of the proposed changes.   

2.  Despite officially being in alpha mode, this library is being used as part of the casper-node formal test platform plus a few exchanges.  Therefore large PRs of this nature will be considered a risk.  Moving forward it is recommended that you submit a set of smaller tightly scoped PR's.  Each PR should have a single clear rationale. 

3.  In respect of CI/CD: integration tests are designed to work against a casper-node network spun up using the [NCTL](https://github.com/casper-network/casper-node/tree/release-1.3.2/utils/nctl) tool.  

4.  The library is being developed as and when I find the time.  As said it is alpha status and needs work primarily in the area of serialisation and chain state queries.   But the objective is to evolve it to a beta version in sync with the v1.4.0 release of casper-node.

5.  We have differing opinions regarding code structure and style.  They are just that, opinions.

**Comment by Pfed-prog** [comment]
@momipsl if it was a community led project, this PR would have been merged. It seems as if you have your own personal motives which are not aligned with the Casper dev community.

**Comment by MrKrautee** [comment]
@momipsl

> We have differing opinions regarding code structure and style.  They are just that, opinions.
Its a shame your are talking about opinions! Real developers know that opinions dont count, only reasons. If you have good reasons to import the way you did, to make a structure like you did, follow no codestyle at all like you did, than document it and all is fine ... otherwise its bad code only, nothing more, at least when it comes to structure, style, oop principles an so on.

so lets talk about those reasons!!

> The library is being developed as and when I find the time
One of the problem: no time and no python developer at all.

Number 2+3 are good reasons but dont explain why you want to wait for the big boom when the project is that big (and for sure not really readable, no professional will help you) that its hard to refactor stuff, but the day will come when its necessary and you will think back to this day..... 

> v0.9.1 has just been released that supersedes a lot of the proposed changes.
no changes at all in the usage of the api.
one import changed and that you have to do some import more explicit and correct. You you imported before, was pretty wrong (no opinion but python). You really should get into python, its not like java, javascript and so on..... your are missing a lot of python benefits because of your bad code style and structure.

**Pull request closed without merging**
